### ISSUE TITLE
Only file and data URLs are supported by the default ESM 

### ISSUE THREAD

**Issue by NoahCardoza** [sindresorhus/terminal-image#38]
Not sure why, but I get this error when I try to import the library:

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. Received protocol 'node:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:750:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}```

**Comment by sindresorhus** [comment]
You need to make sure you're on the latest minor of your Node.js version, for example, Node.js 12.20 or Node.js 14.14.
